Numpy
----

In [1]:
import numpy as np

Lets Do Some Basic Stuff

In [41]:
a = np.array(5)
a

array(5)

In [47]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
a= a.reshape(2,5,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [53]:
print (a.shape)
print (a.ndim)
print (a.size)
print (a.dtype)

(2, 5, 2)
3
20
int64


In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Some Operations

In [57]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [58]:
a

array([20, 30, 40, 50])

In [59]:
b

array([0, 1, 2, 3])

In [ ]:
a-b

array([20, 29, 38, 47])

In [61]:
a+b

array([20, 31, 42, 53])

In [62]:
a*b

array([  0,  30,  80, 150])

In [63]:
c=a*b

In [65]:
c

array([  0,  30,  80, 150])

In [64]:
c > 50

array([False, False,  True,  True])

In [66]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])