In [14]:
import pandas as pd

In [15]:
s1 = pd.Series([1,3,2,5,2,3,4,1,5])

In [16]:
s2 = pd.Series([1,3,2,None,2,3,4,1,5])

In [17]:
len(s1)

9

In [18]:
s1.size

9

In [19]:
s1.count()

np.int64(9)

In [20]:
s1.shape[0]

9

In [21]:
s1.values

array([1, 3, 2, 5, 2, 3, 4, 1, 5])

In [22]:
s2.count()

np.int64(8)

In [27]:
s2.shape[0]

9

In [28]:
s1.values

array([1, 3, 2, 5, 2, 3, 4, 1, 5])

In [29]:
s2.values

array([ 1.,  3.,  2., nan,  2.,  3.,  4.,  1.,  5.])

In [30]:
s3 = pd.Series(['A','B','C'])

In [31]:
s3.values

array(['A', 'B', 'C'], dtype=object)

In [32]:
s3

0    A
1    B
2    C
dtype: object

In [33]:
s3.index

RangeIndex(start=0, stop=3, step=1)

In [34]:
s4 = pd.Series({'A':1,'B':2,"C":3})

In [35]:
s4.values

array([1, 2, 3])

In [36]:
s4.index

Index(['A', 'B', 'C'], dtype='object')

In [37]:
s1

0    1
1    3
2    2
3    5
4    2
5    3
6    4
7    1
8    5
dtype: int64

In [38]:
s1.is_unique

False

In [40]:
s1.is_monotonic_increasing

False

In [42]:
s5 = pd.Series([1,2,3,4,5])

In [43]:
s5.is_monotonic_increasing

True

In [44]:
s5.is_monotonic_decreasing

False